//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace EBHIS
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EBHISEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EBHISEntities object using the connection string found in the 'EBHISEntities' section of the application configuration file.
        /// </summary>
        public EBHISEntities() : base("name=EBHISEntities", "EBHISEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EBHISEntities object.
        /// </summary>
        public EBHISEntities(string connectionString) : base(connectionString, "EBHISEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EBHISEntities object.
        /// </summary>
        public EBHISEntities(EntityConnection connection) : base(connection, "EBHISEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PatientContact> PatientContacts
        {
            get
            {
                if ((_PatientContacts == null))
                {
                    _PatientContacts = base.CreateObjectSet<PatientContact>("PatientContacts");
                }
                return _PatientContacts;
            }
        }
        private ObjectSet<PatientContact> _PatientContacts;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PatientContacts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPatientContacts(PatientContact patientContact)
        {
            base.AddObject("PatientContacts", patientContact);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EBHISModel", Name="PatientContact")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PatientContact : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PatientContact object.
        /// </summary>
        /// <param name="patientID">Initial value of the PatientID property.</param>
        public static PatientContact CreatePatientContact(global::System.Int32 patientID)
        {
            PatientContact patientContact = new PatientContact();
            patientContact.PatientID = patientID;
            return patientContact;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PatientID
        {
            get
            {
                return _PatientID;
            }
            set
            {
                if (_PatientID != value)
                {
                    OnPatientIDChanging(value);
                    ReportPropertyChanging("PatientID");
                    _PatientID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PatientID");
                    OnPatientIDChanged();
                }
            }
        }
        private global::System.Int32 _PatientID;
        partial void OnPatientIDChanging(global::System.Int32 value);
        partial void OnPatientIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Firstname
        {
            get
            {
                return _Firstname;
            }
            set
            {
                OnFirstnameChanging(value);
                ReportPropertyChanging("Firstname");
                _Firstname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Firstname");
                OnFirstnameChanged();
            }
        }
        private global::System.String _Firstname;
        partial void OnFirstnameChanging(global::System.String value);
        partial void OnFirstnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ohternames
        {
            get
            {
                return _Ohternames;
            }
            set
            {
                OnOhternamesChanging(value);
                ReportPropertyChanging("Ohternames");
                _Ohternames = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ohternames");
                OnOhternamesChanged();
            }
        }
        private global::System.String _Ohternames;
        partial void OnOhternamesChanging(global::System.String value);
        partial void OnOhternamesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Surname
        {
            get
            {
                return _Surname;
            }
            set
            {
                OnSurnameChanging(value);
                ReportPropertyChanging("Surname");
                _Surname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Surname");
                OnSurnameChanged();
            }
        }
        private global::System.String _Surname;
        partial void OnSurnameChanging(global::System.String value);
        partial void OnSurnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sex
        {
            get
            {
                return _Sex;
            }
            set
            {
                OnSexChanging(value);
                ReportPropertyChanging("Sex");
                _Sex = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sex");
                OnSexChanged();
            }
        }
        private global::System.String _Sex;
        partial void OnSexChanging(global::System.String value);
        partial void OnSexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BloodGroup
        {
            get
            {
                return _BloodGroup;
            }
            set
            {
                OnBloodGroupChanging(value);
                ReportPropertyChanging("BloodGroup");
                _BloodGroup = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BloodGroup");
                OnBloodGroupChanged();
            }
        }
        private global::System.String _BloodGroup;
        partial void OnBloodGroupChanging(global::System.String value);
        partial void OnBloodGroupChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GenoType
        {
            get
            {
                return _GenoType;
            }
            set
            {
                OnGenoTypeChanging(value);
                ReportPropertyChanging("GenoType");
                _GenoType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GenoType");
                OnGenoTypeChanged();
            }
        }
        private global::System.String _GenoType;
        partial void OnGenoTypeChanging(global::System.String value);
        partial void OnGenoTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PatientPhone
        {
            get
            {
                return _PatientPhone;
            }
            set
            {
                OnPatientPhoneChanging(value);
                ReportPropertyChanging("PatientPhone");
                _PatientPhone = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PatientPhone");
                OnPatientPhoneChanged();
            }
        }
        private Nullable<global::System.Int32> _PatientPhone;
        partial void OnPatientPhoneChanging(Nullable<global::System.Int32> value);
        partial void OnPatientPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NextOfKin
        {
            get
            {
                return _NextOfKin;
            }
            set
            {
                OnNextOfKinChanging(value);
                ReportPropertyChanging("NextOfKin");
                _NextOfKin = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NextOfKin");
                OnNextOfKinChanged();
            }
        }
        private global::System.String _NextOfKin;
        partial void OnNextOfKinChanging(global::System.String value);
        partial void OnNextOfKinChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NOKAddress
        {
            get
            {
                return _NOKAddress;
            }
            set
            {
                OnNOKAddressChanging(value);
                ReportPropertyChanging("NOKAddress");
                _NOKAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NOKAddress");
                OnNOKAddressChanged();
            }
        }
        private global::System.String _NOKAddress;
        partial void OnNOKAddressChanging(global::System.String value);
        partial void OnNOKAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NOKPhone
        {
            get
            {
                return _NOKPhone;
            }
            set
            {
                OnNOKPhoneChanging(value);
                ReportPropertyChanging("NOKPhone");
                _NOKPhone = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NOKPhone");
                OnNOKPhoneChanged();
            }
        }
        private Nullable<global::System.Int32> _NOKPhone;
        partial void OnNOKPhoneChanging(Nullable<global::System.Int32> value);
        partial void OnNOKPhoneChanged();

        #endregion

    
    }

    #endregion

    
}
