#!c:\users\henrio\git-folder\git-folder\face-recognition-attendance-system\env\scripts\python.exe
import pcsv
from jtutils import fix_broken_pipe

if __name__ == "__main__":
    fix_broken_pipe()
    pcsv.pcsv()
