# Generated by Django 4.2.11 on 2024-08-08 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=200, verbose_name='Employee Name')),
                ('dept_name', models.CharField(max_length=100, verbose_name='Department Name')),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_employment', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date of Employment')),
                ('email_address', models.EmailField(help_text='Please use your official email address.', max_length=150, unique=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(help_text='Please type your mobile number.', max_length=15, unique=True)),
                ('is_Admin', models.BooleanField(default=False, verbose_name='Is Admin?')),
                ('is_contract_staff', models.BooleanField(blank=True, default=False, null=True, verbose_name='Contract staff?')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('visitor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('visitor_name', models.CharField(max_length=150, verbose_name='Visitor Name')),
                ('phone_number', models.CharField(help_text='Phone number', max_length=15, unique=True, verbose_name='Phone Number')),
                ('email_address', models.EmailField(help_text='Please provide a valid email address', max_length=200, unique=True, verbose_name='Email Address')),
                ('qr_code', models.CharField(blank=True, max_length=250, null=True, verbose_name='QR Code')),
                ('otp', models.IntegerField(blank=True, default=0, null=True)),
                ('organization', models.CharField(blank=True, max_length=250, null=True)),
                ('dept', models.CharField(blank=True, max_length=150, verbose_name='Department(s) to Visit')),
                ('is_official', models.BooleanField(default=False, verbose_name='Official?')),
                ('comments', models.TextField(blank=True, null=True)),
                ('is_invited', models.BooleanField(blank=True, default=False, null=True, verbose_name='Invited?')),
                ('first_timer', models.BooleanField(blank=True, default=False, null=True, verbose_name='First Timer?')),
                ('date_of_visit', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date of Appointment')),
                ('whom_to_see', models.ManyToManyField(blank=True, to='vms.employee', verbose_name='Employee(s) to See')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='employees',
            field=models.ManyToManyField(related_name='visitors', to='vms.visitor'),
        ),
    ]
