# Generated by Django 4.2.11 on 2024-08-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('employee_name', models.CharField(max_length=200, verbose_name='Employee Name')),
                ('dept_name', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_employment', models.DateTimeField()),
                ('email_address', models.CharField(help_text='Please use your official email address.', max_length=150, unique=True)),
                ('phone_number', models.BigIntegerField(help_text='Please type your mobile number.', max_length=15, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_contract_staff', models.BooleanField(blank=True, default=False, null=True, verbose_name='Contract staff')),
            ],
        ),
    ]
