# Generated by Django 4.2.11 on 2024-08-08 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='date_of_visit',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date of Appointment'),
        ),
    ]
