# Generated by Django 4.2.11 on 2024-08-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(help_text='Please type your mobile number.', max_length=15, unique=True),
        ),
    ]
