# Generated by Django 4.2.11 on 2024-08-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0002_alter_employee_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='is_admin',
            new_name='is_Admin',
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_employment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
