# Generated by Django 4.2.11 on 2024-08-08 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0002_alter_visitor_date_of_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='date_of_visit',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Date of Appointment'),
        ),
    ]
