# Generated by Django 4.2.11 on 2024-08-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0003_alter_visitor_date_of_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employees',
            field=models.ManyToManyField(related_name='employee', to='vms.visitor'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='whom_to_see',
            field=models.ManyToManyField(blank=True, related_name='visitor', to='vms.employee'),
        ),
    ]
