# Generated by Django 4.2.11 on 2024-08-26 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0003_alter_visitor_date_of_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin_visitor',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vms.employee'),
        ),
        migrations.AlterField(
            model_name='checkin_visitor',
            name='time_In',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='checkin_visitor',
            name='time_Out',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='checkin_visitor',
            name='visitor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CheckIn_Visitor', to='vms.visitor'),
        ),
        migrations.AlterField(
            model_name='pending_visitor',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('CHECKOUT', 'checkout')], default='PENDING', max_length=10),
        ),
    ]
