# Generated by Django 4.2.11 on 2024-08-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0004_alter_employee_employees_alter_visitor_whom_to_see'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='whom_to_see',
        ),
        migrations.AddField(
            model_name='visitor',
            name='whom_to_see',
            field=models.CharField(blank=True, max_length=150, verbose_name='Host Employee'),
        ),
    ]
