# Generated by Django 4.2.11 on 2024-08-07 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0004_alter_employee_date_of_employment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_employment',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
