# Generated by Django 4.2.11 on 2024-09-25 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0004_alter_checkin_visitor_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin_visitor',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vms.employee'),
        ),
        migrations.AlterField(
            model_name='pending_visitor',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('CHECKOUT', 'Checkout'), ('DECLINE', 'Decline')], default='PENDING', max_length=10),
        ),
    ]
