# Generated by Django 4.2.11 on 2024-08-08 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0005_remove_visitor_whom_to_see_visitor_whom_to_see'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employees',
            new_name='whom_to_see',
        ),
    ]
