# Generated by Django 4.2.11 on 2024-09-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0005_alter_checkin_visitor_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_visitor',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('CHECKOUT', 'Checkout'), ('DECLINED', 'Decline')], default='PENDING', max_length=10),
        ),
    ]
