# Generated by Django 4.2.11 on 2024-08-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0005_alter_employee_date_of_employment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_employment',
            field=models.DateTimeField(blank=True, default='<function now at 0x0000025031911300>', null=True),
        ),
    ]
