# Generated by Django 4.2.11 on 2024-08-07 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0006_alter_employee_date_of_employment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_employment',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 7, 13, 9, 8, 96395, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
