# Generated by Django 4.2.11 on 2024-10-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0006_alter_pending_visitor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin_visitor',
            name='time_Out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_Admin',
            field=models.BooleanField(default=False, verbose_name='Admin?'),
        ),
        migrations.AlterField(
            model_name='pending_visitor',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('CHECKOUT', 'Checkout'), ('DECLINED', 'Declined')], default='PENDING', max_length=10),
        ),
    ]
