# Generated by Django 4.2.11 on 2024-08-11 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0007_remove_employee_whom_to_see_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending_Visitor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pending_Visitor', to='vms.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn_Visitor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_In', models.DateTimeField()),
                ('time_Out', models.DateTimeField()),
                ('is_pending', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_by', models.CharField(blank=True, max_length=150)),
                ('visitor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Visitor_To_CheckIn', to='vms.visitor')),
            ],
        ),
    ]
