# Generated by Django 4.2.11 on 2024-08-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0007_alter_employee_date_of_employment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_employment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
