# Generated by Django 4.2.11 on 2024-08-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0009_alter_employee_date_of_employment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='dept',
            field=models.ManyToManyField(blank=True, to='vms.employee', verbose_name='Dept(s) To Visit'),
        ),
    ]
