# Generated by Django 4.2.11 on 2024-08-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0010_alter_visitor_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='email_address',
            field=models.CharField(help_text='Please provide a valid email address', max_length=200, unique=True, verbose_name='Email Address'),
        ),
    ]
