# Generated by Django 4.2.11 on 2024-08-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0011_alter_visitor_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='date_of_visit',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
