# Generated by Django 4.2.11 on 2024-08-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0012_alter_visitor_date_of_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='dept',
        ),
        migrations.AddField(
            model_name='visitor',
            name='dept',
            field=models.CharField(blank=True, max_length=100, verbose_name='Dept(s) To Visit'),
        ),
    ]
