# Generated by Django 4.2.11 on 2024-08-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0013_remove_visitor_dept_visitor_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='dept',
        ),
        migrations.AddField(
            model_name='visitor',
            name='dept',
            field=models.ManyToManyField(blank=True, to='vms.employee', verbose_name='Dept(s) To Visit'),
        ),
    ]
